[package]
name = "ekiden-keymanager"
version = "0.3.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]

[dependencies]
ekiden-crypto = { path = "../ekiden_crypto" }

serde = "1.0.71"
serde_derive = "1.0"
serde_bytes = "~0.10"
rand = "0.6.5"
rustc-hex = "2.0.1"
x25519-dalek = "0.5.1"
