version: 2
jobs:
  build:
    environment:
      PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
    docker:
      - image: oasislabs/rust:latest
    resource_class: xlarge
    steps:
      # Check out source from github
      - checkout

      # Check style
      - run:
          name: Rustfmt
          command: cargo fmt -- --check

      # Build
      - run:
          name: Build
          command: cargo build

      # Test
      - run:
          name: Cargo tests
          command: cargo test
