version: 2.1


executors:
  rust:
    environment:
      PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
    docker:
      - image: oasislabs/rust:latest
    resource_class: xlarge


jobs:
  build:
    executor: rust
    steps:
      - checkout
      - run:
          name: Rustfmt
          command: cargo fmt -- --check
      - run:
          name: Build
          command: cargo build
      - run:
          name: Test
          command: cargo test


workflows:
  version: 2

  build:
    jobs:
      - build
